---
title: Zetmel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  reviews:
    title: Reviews
    output: false
reviews_order:
  - Ken
  - Mike2
  - Zaid
  - Mike1
comments_order:
  - Inaamul_Hassan
  - Huzni
  - Senthan
  - Hasanul_Bannah
  - Abdul_Rahman
  - Musharrif
  - Sasvathan
  - Hifans
  - Shifrin
  - Ashraq
  - Majaz
  - Nasmaan
description: 
baseurl: 
url: https://zetmel.com
disqus_enabled: false
disqus_shortname: zetmel
markdown: kramdown
permalink: pretty
sass:
  sass_dir: assets/_scss
